---
abstract: 'A more knowledgeable perldoc'
author:
  - 'Marcel Gruenauer <marcel@cpan.org>'
build_requires:
  Test::More: 0.94
configure_requires:
  ExtUtils::MakeMaker: 6.58
dynamic_config: 1
generated_by: 'ExtUtils::MakeMaker version 6.6302, CPAN::Meta::Converter version 2.120921'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: App-perlfind
no_index:
  directory:
    - t
    - inc
requires:
  Class::Trigger: 0
  Module::Pluggable: 0
  Pod::Cpandoc: 0
  Pod::Functions: 0
  Test::Differences: 0
  parent: 0
version: 2.05
